server:
  port: 10014
  servlet:
    context-path: /psmgr
  undertow:
    direct-buffers: true
    max-http-post-size: -1B
  ssl:
    enabled: false

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  thymeleaf:
    suffix: .htm
    cache: false
    mode: HTML
    servlet:
      content-type: text/html; charset=utf-8
  gson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    serialize-nulls: true
    pretty-printing: true

logging:
  path: /home/stgoder/psmgr/logs
  file: /home/stgoder/psmgr/logs/psmgr.log
  level:
    root: INFO

myConfig:
  test-mode: true
  #ffmpeg-path: 'D:\sof\ffmpeg4.1.3\bin\ffmpeg.exe'
  ffmpeg-path: '/home/stgoder/sof/ffmpeg4.1.3/ffmpeg'
  #pslog-path: 'D:\psmgr\pslog'
  pslog-path: '/home/stgoder/psmgr/pslog'
  #record-path: 'D:\psmgr\record'
  record-path: '/home/stgoder/psmgr/record'
  #hls-path: 'D:\psmgr\hls'
  hls-path: '/home/stgoder/psmgr/hls'
  hls-time: 10
  local-ipv4: '192.168.1.214'
  with-nginx: true
  nginx-path: '/home/stgoder/psmgr/nginx'
  ds:
    sqlite0:
      db-file-path: /home/stgoder/psmgr/sqlite0.db
      #db-file-path: D:\home\stgoder\psmgr\sqlite0.db
      pool-size: 3
      pool-name: sqlite0